repos:
  - repo: local
    hooks:
      - id: spotless-java-staged
        name: Spotless Format Staged Java
        entry: ./spotless-staged.sh
        language: script
        files: \.java$
        description: Automatically formats staged Java files using mvnw and Spotless.
        verbose: true